"""initial schema: content, audio, learners, audit + content-rule triggers and view

Besides the tables (autogenerated from vv_backend.db.models), this migration adds
the database-level guarantees for the non-negotiable content rules:
- editing verified content resets `verified` (shlokas, word_analyses; word
  changes reset the parent shloka), so no code path can forget it;
- `content_audit` is append-only;
- learners read through the `verified_shlokas` view;
- `updated_at` is maintained by the database.

Revision ID: 0001
Revises:
Create Date: 2026-10-07 06:15:26.741631
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SHLOKA_CONTENT = ("title", "devanagari", "iast", "translation", "source_id", "source_ref")
ANALYSIS_CONTENT = ("pada_iast", "lemma", "morphology", "meaning", "explanation")


def _changed(cols: tuple[str, ...]) -> str:
    return " OR ".join(f"NEW.{c} IS DISTINCT FROM OLD.{c}" for c in cols)


RULES_UP = [
    """
    CREATE FUNCTION set_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        NEW.updated_at := now();
        RETURN NEW;
    END $$
    """,
    # Editing verified content (without re-verifying in the same statement) resets it.
    f"""
    CREATE FUNCTION shlokas_reset_verified() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        IF OLD.verified AND NEW.verified AND ({_changed(SHLOKA_CONTENT)}) THEN
            NEW.verified := false;
            NEW.verified_by := NULL;
            NEW.verified_at := NULL;
        END IF;
        RETURN NEW;
    END $$
    """,
    f"""
    CREATE FUNCTION word_analyses_reset_verified() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        IF OLD.verified AND NEW.verified AND ({_changed(ANALYSIS_CONTENT)}) THEN
            NEW.verified := false;
            NEW.verified_by := NULL;
            NEW.verified_at := NULL;
        END IF;
        RETURN NEW;
    END $$
    """,
    # The recited words are part of the shloka's content: changing them un-verifies it.
    """
    CREATE FUNCTION shloka_words_reset_parent() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        UPDATE shlokas SET verified = false, verified_by = NULL, verified_at = NULL
         WHERE verified AND id IN (
            SELECT x FROM unnest(ARRAY[
                CASE WHEN TG_OP <> 'DELETE' THEN NEW.shloka_id END,
                CASE WHEN TG_OP <> 'INSERT' THEN OLD.shloka_id END]) AS x
            WHERE x IS NOT NULL);
        RETURN NULL;
    END $$
    """,
    """
    CREATE FUNCTION content_audit_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        RAISE EXCEPTION 'content_audit is append-only';
    END $$
    """,
    "CREATE TRIGGER shlokas_updated_at BEFORE UPDATE ON shlokas "
    "FOR EACH ROW EXECUTE FUNCTION set_updated_at()",
    "CREATE TRIGGER word_analyses_updated_at BEFORE UPDATE ON word_analyses "
    "FOR EACH ROW EXECUTE FUNCTION set_updated_at()",
    "CREATE TRIGGER shlokas_reset_verified BEFORE UPDATE ON shlokas "
    "FOR EACH ROW EXECUTE FUNCTION shlokas_reset_verified()",
    "CREATE TRIGGER word_analyses_reset_verified BEFORE UPDATE ON word_analyses "
    "FOR EACH ROW EXECUTE FUNCTION word_analyses_reset_verified()",
    # expected_phonemes is derived data (scoring service), so it is not listed here.
    "CREATE TRIGGER shloka_words_reset_parent AFTER INSERT OR DELETE OR UPDATE OF "
    "shloka_id, position, surface_iast, surface_devanagari ON shloka_words "
    "FOR EACH ROW EXECUTE FUNCTION shloka_words_reset_parent()",
    "CREATE TRIGGER content_audit_append_only BEFORE UPDATE OR DELETE ON content_audit "
    "FOR EACH ROW EXECUTE FUNCTION content_audit_append_only()",
    # Learner-facing reads: verified rows only, without internal review fields.
    """
    CREATE VIEW verified_shlokas AS
    SELECT id, slug, title, devanagari, iast, translation, source_id, source_ref,
           verified_at, updated_at
      FROM shlokas
     WHERE verified
    """,
]

RULES_DOWN = [
    "DROP VIEW IF EXISTS verified_shlokas",
    "DROP TRIGGER IF EXISTS content_audit_append_only ON content_audit",
    "DROP TRIGGER IF EXISTS shloka_words_reset_parent ON shloka_words",
    "DROP TRIGGER IF EXISTS word_analyses_reset_verified ON word_analyses",
    "DROP TRIGGER IF EXISTS shlokas_reset_verified ON shlokas",
    "DROP TRIGGER IF EXISTS word_analyses_updated_at ON word_analyses",
    "DROP TRIGGER IF EXISTS shlokas_updated_at ON shlokas",
    "DROP FUNCTION IF EXISTS content_audit_append_only()",
    "DROP FUNCTION IF EXISTS shloka_words_reset_parent()",
    "DROP FUNCTION IF EXISTS word_analyses_reset_verified()",
    "DROP FUNCTION IF EXISTS shlokas_reset_verified()",
    "DROP FUNCTION IF EXISTS set_updated_at()",
]


def upgrade() -> None:
    op.create_table(
        "content_audit",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("actor_clerk_id", sa.String(length=64), nullable=False),
        sa.Column("entity", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column(
            "diff",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_audit")),
    )
    op.create_index(
        "ix_content_audit_entity", "content_audit", ["entity", "entity_id"], unique=False
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("license", sa.Text(), nullable=False),
        sa.Column("license_url", sa.Text(), nullable=True),
        sa.Column("retrieved_at", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('text', 'audio', 'tool', 'model')", name=op.f("ck_sources_kind")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("key", name=op.f("uq_sources_key")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("clerk_user_id", sa.String(length=64), nullable=False),
        sa.Column(
            "timezone", sa.String(length=64), server_default=sa.text("'UTC'"), nullable=False
        ),
        sa.Column(
            "recording_consent", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("consent_version", sa.String(length=20), nullable=True),
        sa.Column("consent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT recording_consent OR (consent_version IS NOT NULL AND consent_at IS NOT NULL)",
            name=op.f("ck_users_consent_recorded"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("clerk_user_id", name=op.f("uq_users_clerk_user_id")),
    )
    op.create_table(
        "shlokas",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("devanagari", sa.Text(), nullable=False),
        sa.Column("iast", sa.Text(), nullable=False),
        sa.Column("translation", sa.Text(), nullable=True),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_ref", sa.Text(), nullable=False),
        sa.Column("verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("verified_by", sa.String(length=64), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name=op.f("ck_shlokas_slug_format")
        ),
        sa.CheckConstraint(
            "NOT verified OR (verified_by IS NOT NULL AND verified_at IS NOT NULL)",
            name=op.f("ck_shlokas_verified_has_reviewer"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_shlokas_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shlokas")),
        sa.UniqueConstraint("slug", name=op.f("uq_shlokas_slug")),
    )
    op.create_table(
        "audio_assets",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("shloka_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("r2_key", sa.String(length=300), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("license", sa.Text(), nullable=True),
        sa.Column("attribution", sa.Text(), nullable=True),
        sa.Column("reciter", sa.String(length=200), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("codec", sa.String(length=20), nullable=True),
        sa.Column("sample_rate", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "is_active_reference", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT is_active_reference OR kind = 'reference'",
            name=op.f("ck_audio_assets_active_is_reference"),
        ),
        sa.CheckConstraint(
            "kind <> 'test' OR (license IS NOT NULL AND attribution IS NOT NULL)",
            name=op.f("ck_audio_assets_test_has_license"),
        ),
        sa.CheckConstraint(
            "kind IN ('reference', 'test', 'user_consented')", name=op.f("ck_audio_assets_kind")
        ),
        sa.CheckConstraint(
            "sha256 IS NULL OR sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_audio_assets_sha256_hex")
        ),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms > 0", name=op.f("ck_audio_assets_duration_positive")
        ),
        sa.ForeignKeyConstraint(
            ["shloka_id"],
            ["shlokas.id"],
            name=op.f("fk_audio_assets_shloka_id_shlokas"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audio_assets")),
        sa.UniqueConstraint("r2_key", name=op.f("uq_audio_assets_r2_key")),
    )
    op.create_index(
        "uq_audio_assets_active_reference",
        "audio_assets",
        ["shloka_id"],
        unique=True,
        postgresql_where=sa.text("is_active_reference"),
    )
    op.create_table(
        "shloka_words",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("shloka_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("surface_iast", sa.String(length=200), nullable=False),
        sa.Column("surface_devanagari", sa.String(length=200), nullable=False),
        sa.Column("expected_phonemes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint("position >= 0", name=op.f("ck_shloka_words_position_nonneg")),
        sa.ForeignKeyConstraint(
            ["shloka_id"],
            ["shlokas.id"],
            name=op.f("fk_shloka_words_shloka_id_shlokas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shloka_words")),
        sa.UniqueConstraint("shloka_id", "position", name="uq_shloka_words_shloka_position"),
    )
    op.create_table(
        "attempts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("shloka_id", sa.UUID(), nullable=False),
        sa.Column("reference_audio_id", sa.UUID(), nullable=True),
        sa.Column("recording_r2_key", sa.String(length=300), nullable=True),
        sa.Column("overall_score", sa.SmallInteger(), nullable=False),
        sa.Column("scorer_version", sa.String(length=40), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms > 0", name=op.f("ck_attempts_duration_positive")
        ),
        sa.CheckConstraint("overall_score BETWEEN 0 AND 100", name=op.f("ck_attempts_score_range")),
        sa.ForeignKeyConstraint(
            ["reference_audio_id"],
            ["audio_assets.id"],
            name=op.f("fk_attempts_reference_audio_id_audio_assets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["shloka_id"],
            ["shlokas.id"],
            name=op.f("fk_attempts_shloka_id_shlokas"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_attempts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempts")),
    )
    op.create_index("ix_attempts_user_created", "attempts", ["user_id", "created_at"], unique=False)
    op.create_table(
        "audio_word_marks",
        sa.Column("audio_asset_id", sa.UUID(), nullable=False),
        sa.Column("shloka_word_id", sa.UUID(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "start_ms >= 0 AND end_ms > start_ms", name=op.f("ck_audio_word_marks_span")
        ),
        sa.ForeignKeyConstraint(
            ["audio_asset_id"],
            ["audio_assets.id"],
            name=op.f("fk_audio_word_marks_audio_asset_id_audio_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shloka_word_id"],
            ["shloka_words.id"],
            name=op.f("fk_audio_word_marks_shloka_word_id_shloka_words"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "audio_asset_id", "shloka_word_id", name=op.f("pk_audio_word_marks")
        ),
    )
    op.create_table(
        "word_analyses",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("shloka_word_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("pada_iast", sa.String(length=200), nullable=False),
        sa.Column("lemma", sa.String(length=200), nullable=True),
        sa.Column(
            "morphology",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("analysis_tool", sa.String(length=50), nullable=True),
        sa.Column("analysis_tool_version", sa.String(length=20), nullable=True),
        sa.Column("meaning", sa.Text(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("explanation_model", sa.String(length=100), nullable=True),
        sa.Column("explanation_prompt_version", sa.String(length=20), nullable=True),
        sa.Column("verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("verified_by", sa.String(length=64), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT verified OR (verified_by IS NOT NULL AND verified_at IS NOT NULL)",
            name=op.f("ck_word_analyses_verified_has_reviewer"),
        ),
        sa.ForeignKeyConstraint(
            ["shloka_word_id"],
            ["shloka_words.id"],
            name=op.f("fk_word_analyses_shloka_word_id_shloka_words"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_word_analyses")),
        sa.UniqueConstraint("shloka_word_id", "position", name="uq_word_analyses_word_position"),
    )
    op.create_table(
        "word_labels",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("audio_asset_id", sa.UUID(), nullable=False),
        sa.Column("shloka_word_id", sa.UUID(), nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("issue_code", sa.String(length=40), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("labeled_by", sa.String(length=64), nullable=False),
        sa.Column(
            "labeled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["audio_asset_id"],
            ["audio_assets.id"],
            name=op.f("fk_word_labels_audio_asset_id_audio_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shloka_word_id"],
            ["shloka_words.id"],
            name=op.f("fk_word_labels_shloka_word_id_shloka_words"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_word_labels")),
        sa.UniqueConstraint(
            "audio_asset_id", "shloka_word_id", "labeled_by", name="uq_word_labels_per_labeler"
        ),
    )
    op.create_table(
        "attempt_word_scores",
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("shloka_word_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.SmallInteger(), nullable=False),
        sa.Column("issue_code", sa.String(length=40), nullable=True),
        sa.Column("issue_text", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "score BETWEEN 0 AND 100", name=op.f("ck_attempt_word_scores_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attempts.id"],
            name=op.f("fk_attempt_word_scores_attempt_id_attempts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shloka_word_id"],
            ["shloka_words.id"],
            name=op.f("fk_attempt_word_scores_shloka_word_id_shloka_words"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "attempt_id", "shloka_word_id", name=op.f("pk_attempt_word_scores")
        ),
    )
    for stmt in RULES_UP:
        op.execute(stmt)


def downgrade() -> None:
    for stmt in RULES_DOWN:
        op.execute(stmt)
    op.drop_table("attempt_word_scores")
    op.drop_table("word_labels")
    op.drop_table("word_analyses")
    op.drop_table("audio_word_marks")
    op.drop_index("ix_attempts_user_created", table_name="attempts")
    op.drop_table("attempts")
    op.drop_table("shloka_words")
    op.drop_index(
        "uq_audio_assets_active_reference",
        table_name="audio_assets",
        postgresql_where=sa.text("is_active_reference"),
    )
    op.drop_table("audio_assets")
    op.drop_table("shlokas")
    op.drop_table("users")
    op.drop_table("sources")
    op.drop_index("ix_content_audit_entity", table_name="content_audit")
    op.drop_table("content_audit")
